do not install convience packages on fedora
As the vim packaging is broken:

    [vagrant@jhoblitt-syv-f25 ~]$ sudo dnf install vim-enhanced
    Puppet Labs PC1 Repository fedora f25 - x86_64  8.0 MB/s | 559 kB     00:00
    Fedora 25 - x86_64 - Updates                     51 MB/s |  25 MB     00:00
    Fedora 25 - x86_64                               92 MB/s |  50 MB     00:00
    Last metadata expiration check: 0:00:20 ago on Fri Aug 11 18:56:12 2017.
    Dependencies resolved.
    ================================================================================
     Package              Arch         Version                  Repository     Size
    ================================================================================
    Installing:
     vim-common           x86_64       2:8.0.823-1.fc25         updates       6.7 M
     vim-enhanced         x86_64       2:8.0.823-1.fc25         updates       1.3 M
     vim-filesystem       x86_64       2:8.0.823-1.fc25         updates        35 k

    Transaction Summary
    ================================================================================
    Install  3 Packages

    Total download size: 8.0 M
    Installed size: 31 M
    Is this ok [y/N]: y
    Downloading Packages:
    (1/3): vim-filesystem-8.0.823-1.fc25.x86_64.rpm 2.2 MB/s |  35 kB     00:00
    (2/3): vim-enhanced-8.0.823-1.fc25.x86_64.rpm    13 MB/s | 1.3 MB     00:00
    (3/3): vim-common-8.0.823-1.fc25.x86_64.rpm      26 MB/s | 6.7 MB     00:00
    --------------------------------------------------------------------------------
    Total                                            19 MB/s | 8.0 MB     00:00
    Running transaction check
    Transaction check succeeded.
    Running transaction test
    The downloaded packages were saved in cache until the next successful transaction.
    You can remove cached packages by executing 'dnf clean packages'.
    Error: Transaction check error:
      file /usr/share/man/man1/vim.1.gz from install of vim-common-2:8.0.823-1.fc25.x86_64 conflicts with file from package vim-minimal-2:7.4.1989-2.fc25.x86_64

    Error Summary
    -------------